# travis.yml for https://github.com/giesselmann/STRique
language: python
sudo: true

matrix:
  include:
  # Linux builds
  - name : "Python 3.6 Bionic"
    os: linux
    language: python
    dist: bionic
    python: "3.6"
    compiler: gcc
    addons: &gcc7
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - gcc-7
    env:
      - CXX_COMPILER='g++-7'
      - C_COMPILER='gcc-7'
      - Fortran_COMPILER='gfortran-7'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.6
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - name : "Python 3.7 Bionic"
    os: linux
    language: python
    dist: bionic
    python: "3.7"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - gcc-7
    env:
      - CXX_COMPILER='g++-7'
      - C_COMPILER='gcc-7'
      - Fortran_COMPILER='gfortran-7'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - name : "Python 3.8 Bionic"
    os: linux
    language: python
    dist: bionic
    python: "3.8"
    compiler: gcc
    addons: &gcc6
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
          - gcc-7
    env:
      - CXX_COMPILER='g++-7'
      - C_COMPILER='gcc-7'
      - Fortran_COMPILER='gfortran-7'
      - BUILD_TYPE='Release'
      - COVERAGE=OFF
      - PYTHON=3.7
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - name : "Python 3.6 macOS"
    os: osx
    osx_image: xcode10.2
    env:
        - MATRIX_EVAL="brew install gcc6 && CC=gcc-7 && CXX=g++-7"
        - CXX_COMPILER='g++-7'
        - C_COMPILER='gcc-7'
        - Fortran_COMPILER='gfortran-7'
        - BUILD_TYPE='Release'
        - COVERAGE=OFF
        - PYTHON=3.6
    language: shell


notifications:
  email: false

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - pip3 install setuptools wheel
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - python3 setup.py install

script:
  - python3 scripts/STRique_test.py
  - python3 scripts/STRique.py index data/ > data/reads.fofn
  - cat data/c9orf72.sam | python3 scripts/STRique.py count data/reads.fofn models/r9_4_450bps.model configs/repeat_config.tsv --config configs/STRique.json --mod_model models/r9_4_450bps_mCpG.model --log_level debug
